$script = <<-SCRIPT
 cat /home/vagrant/.ssh/key.pub >> /home/vagrant/.ssh/authorized_keys
 SCRIPT
#  curl -sfL https://get.k3s.io | sh -
$k3s_setup = <<-SCRIPT
  curl -sfL https://get.k3s.io | sh -
SCRIPT

$worker_setup = <<-SCRIPT
  k3s_url=https://$1:6443
  k3s_token=`sudo cat /var/lib/rancher/k3s/server/node-token`
  curl -sfL https://get.k3s.io | K3S_URK=${k3s_url} K3S_TOKEN=${k3s_token} sh -
SCRIPT

require 'yaml'

conf = YAMl.load_file(FILE.join(FILE.dirname(__FILE__), "config.yaml"))

Vagrant.configure("2") do |config|
  config.env.enable
  config.vm.box = ENV["box"]
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/key.pub"
  # config.vm.synced_folder "hash_node/", "/var/lib/rancher/k3s/server"
#   config.vm.provision "file", source: "~/Desktop/inception-of-things/script.sh", destination: "~/run.sh"
  # config.trigger.after :up do |trigger|
  #   trigger.run_remote = {inline: $k3s_setup}
  # end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.42.110"
    master.vm.provision "shell", inline: $k3s_setup
    # config.vm.synced_folder "hash_node/", "/var/lib/rancher/k3s/server"
    master.trigger.after :up do |trigger|
      trigger.run_remote = {inline: $script}
    end
  end
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: "192.168.42.111"
    # worker.vm.provision "file", source: "hash_node/node-token", destination: "/home/vagrant/node-token"
    # worker.vm.provision "shell" do |s|
    #   s.inline = $worker_setup
    #   s.args = "192.168.42.110"
    # end
    worker.trigger.after :up do |trigger|
      trigger.run_remote = {inline: $worker_setup, args: "192.168.42.110"}
    end
  end
end
