$script = <<-SCRIPT
 cat /home/vagrant/.ssh/key.pub >> /home/vagrant/.ssh/authorized_keys
 SCRIPT
#  curl -sfL https://get.k3s.io | sh -

require 'yaml'

# conf = YAMl.load_file(FILE.join(FILE.dirname(__FILE__), "config.yaml"))

Vagrant.configure("2") do |config|
  config.env.enable
  config.vm.box = ENV["box"]
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/key.pub"
#   config.vm.provision "file", source: "~/Desktop/inception-of-things/script.sh", destination: "~/run.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.42.110"
    # master.vm.provision "shell", inline: $script
    master.trigger.after :up do |trigger|
      trigger.run_remote = {inline: $script}
    end
  end
end
