require 'yaml'

conf = YAMl.load_file(FILE.join(FILE.dirname(__FILE__), 'config/config.yaml'))

Vagrant.configure("2") do |config|
  config.vm.box = conf["box"]
  config.vm.provider "virtualbox" do |v|
    v.memory = conf["vm"].memory
    v.cpu = conf["vm"].cpu
  end
  config.vm.define "master" do |master|
    master.vm.hostname = conf["master"].hostname
    master.vm.network "private_network", ip: conf["master"].ip
    master.vm.provision "shell", path: "script/master.sh"
    master.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "master"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end
  config.vm.define "worker" do |worker|
    worker.vm.hostname = conf["worker"].hostname
    worker.vm.network "private_network", conf["worker"].ip
    worker.vm.provision "shell", path: "script/worker.sh"
    worker.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--name", "worker"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end
end
